#import "@local/common:0.0.0": *
#import "@local/theorem-shorthands-en:0.0.0": *
#import "@preview/equate:0.3.1": equate
#import "@preview/commute:0.3.0": *

#show: theorem

#set page("a4", margin: 1in, numbering: "1")
#set text(font: "TeX Gyre Schola")
#set heading(numbering: "1.")
#show heading: it => {
  it
  v(5pt)
}

#set math.equation(numbering: "(1)", supplement: none)
#show: equate.with(sub-numbering: false, number-mode: "label")

#let st(cnt, class: []) = $stretch(->)_(#cnt)^(#class)$
#let nn(X) = $cal(N)(#X)$
#let SS = $cal(S)$
#let CC = $cal(C)$
#let FF = $cal(F)$

#align(center)[
  #text(size: 22pt)[*Continuous Convergence and Curried Functional Spaces*]
  #v(.5in)
]

= Introduction

= General curried functions

#def[
  Let $n in NN_0 = {0, 1, 2, ...}$. The set $H_n (RR)$ of _curried $n$-variable functions_ is a topological vector space defined recursively as follows:
  - If $n = 0$, we set $H_0 (RR) = RR$;
  - If $H_n (RR)$ is defined, we let $H_(n+1) (RR)$ to be the set of all functions from $RR$ to $H_n (RR)$. This set is given the pointwise linear structure and the topology of pointwise convergence. @pwhaus and @pwtvs ensure that $H_(n+1)(RR)$ is a Hausdorff topological vector space.
]

#def[
  Let $tilde(f) : RR^n -> RR$ be a function. Define
  $
    gamma(tilde(f))(x_1)(x_2)...(x_n) = tilde(f)(x_1, x_2, ..., x_n).
  $
  Then $gamma : "Hom"(RR^n, RR) -> H_n (RR)$ is clearly a bijection. The function $f = gamma(tilde(f))$ will be called the _curried version_ of $tilde(f)$.
]

#lm[
  For every $n in NN_0$, the space $H_n (RR)$ is locally compact.
]
#pf[
  An easy proof by induction over $n$.
]

#lm[
  For every $n >= 1$, the space $H_n (RR)$ is not metrizable.
]
#pf[
  
]

= Continuous curried functions

#def[
  Let $n in NN_0$. The set $C_n (RR)$ of _curried continuous functions_ is a Hausdorff topological vector space defined recursively as follows:
  - If $n = 0$, we set $C_0 (RR) = RR$.
  - If $C_n (RR)$ is defined, we set $C_(n+1) (RR) = CC(RR, C_n (RR))$, endowed with pointwise linear structure and the compact-open topology (see @coapp). @cohaus and @cotvs ensure that $C_(n+1)(RR)$ is a Hausdorff topological vector space, provided that $C_n (RR)$ is.
]

#lm[
  Let $X, Y$ be topological spaces such that $X$ is first countable. Then a sequence ${f_k}_(k in NN) subset CC(X,Y)$ converges to a function $f in CC(X,Y)$ if and only if $f_k (x_k) st(k -> oo) f(x)$ whenever $x_k st(k -> oo) x$ in $X$.
] <simul>
#pf[
  First, let $F$ be the derived filter of ${f_k}_(k in NN)$ and suppose that $F$ converges to a function $f in CC(X,Y)$. Consider a sequence ${x_k}_(k in NN)$ converging to $x in X$, with its derived filter $P$. Now let $V$ be a neighborhood of $f(x)$ in $Y$. By @cofilter, we have $F(P) -> f(x)$, and so $V in F(P)$. This means that $V$ contains an element of the base of $F(P)$, namely a set
  $
    B_(n_0, m_0) = {f_n (x_m) mid(|) n >= n_0, hs m >= m_0}.
  $
  Hence, for $k >= max(n_0\, m_0)$, we have $f_k (x_k) in V$, as desired.\

  Conversely, suppose that $f_k (x_k) st(k -> oo) f(x)$ whenever $x_k st(k -> oo) x in X$. First let us show that for any subsequence ${f_(n_k)}_(k in NN)$, we have $f_(n_k)(x_k) st(k -> oo) f(x)$.\
  To this end, let $n in NN$. We let $z_n = x_(phi(n))$, where $phi(n)$ is the minimal number of those $k in NN$ that satisfy $n <= n_k$. We clearly see that $n_1 >= n_2$ implies $phi(n_1) >= phi(n_2)$ and that $phi(n_k) = k$ for all $k in NN$. Therefore, the sequence ${z_n}_(n in NN)$ converges to $x$. Hence we have $f_k (z_k) st(k -> oo) f(x)$, and so
  $
    f_(n_k) (x_k) = f_(n_k) (z_(n_k)) st(k -> oo) f(x).
  $ <subseq>
  Now, to show that $f_k -> f$ in $CC(X,Y)$, we need to show that the derived filter $F$ generated by the sets $C_n = {f_k mid(|) k >= n}$ converges to $f$. To this end, let $P$ be a filter in $X$ converging to a point $x in X$. Note that since $X$ is first countable, the filter $P$ has a countable base ${A_m}_(m in NN)$ of neighborhoods of $x$. To show that $F(P)$ converges to $f(x)$, assume the contrary. Then some neighborhood $V$ of $f(x)$ does not lie in $F(P)$, which is to say that for all $n, m in NN$, we have $C_n (A_m) subset.not V$. That means that for all $n,m in NN$, there are $k_m >= m$ and $x_m in A_m$ such that $f_(k_n)(x_m) in.not V$.\
  In particular, we have $f_(k_n)(x_n) in.not V$ for all $n in NN$. At the same time, since the sets $A_n$ generate $P$, we see that $x_n st(n -> oo) x$, so we must have $f_(k_n)(x_n) st(n -> oo) f(x)$ by (@subseq), a contradiction.
]

#cor[
  From the above lemma we conclude that if $n >= 1$, a sequence of functions ${f_k}_(k = 1)^oo$ in $C_n (RR)$ converges to $f in C_n (RR)$ if and only if for any sequence ${x_k}_(k = 1)^oo subset RR$ converging to $x in RR$, we have $f_k (x_k) st(k -> oo) f(x)$ in $C_(n-1)(RR)$.
]

#exam[
  The topology on $C_n (RR)$ is finer than the topology induced from $H_n (RR)$, and does not coincide with it, unless $n = 0$. To see this, take $n = 1$ and consider the classical function
  $
    phi (x) = cases(
      exp(1/(abs(x)^2 - 1))\, #h(10pt)& abs(x) < 1,
      0\, & abs(x) >= 1.
    )
  $
  This is a $C^oo (RR)$ function supported on $[-1,1]$. Its graph looks as follows:
  #figure(
    image("./figures/bump.pdf")
  )
  Now consider the following sequence of functions:
  $
    f_k (x) = e dot phi(k dot (x - 1/k)).
  $
  Clearly, $f_k$ is infinitely differentiable on $RR$, supported on $[0,2\/k]$, and has a maximum at $x = 1\/k$ with $f_k (1\/k) = 1$. It is clear that for all $x in RR$, we have $f_k (x) st(k -> oo) 0$, so $f_k -> 0$ in the topology induced from $H_1 (RR)$. However, $f_k$ do not converge to $0$ in the native topology of $C_1 (RR)$. To see this, take $x_k = 1\/k$ and observe that $f_k (x_k) equiv 1 != 0$.\

  A similar argument applies for any other $n >= 2$. Hence we conclude that $C_n (RR)$ is not a subspace of $H_n (RR)$.
]

#prop[
  Let $n in NN_0$. Then the map
  $
    gamma : CC(RR^n, RR) -> C_n (RR)
  $
  defined by $gamma(f)(x_1)(x_2)...(x_n) = f(x_1, ..., x_n)$, is well-defined and is a homeomorphism.
] <cogamma>
#pf[
  If $n = 0$, the statement is trivial. Assume it is proven for $C_n (RR)$. By @curry, we have
  $
    CC(RR^(n+1), RR) = CC(RR times RR^n, RR) tilde.equiv CC(RR, CC(RR^n, RR)) tilde.equiv CC(RR, C_n (RR)) = C_(n+1)(RR),
  $
  q.e.d.
]

#lm[
  For every $n in NN_0$, the space $C_n (RR)$ is locally compact.
]
#pf[
  An easy proof by induction over $n$.
]

== Differentiable functions

#def[
  Let $m in NN_0$ and $n in NN_0$. The set $D^m_n (RR)$ of _curried $m$ times differentiable functions_ is a topological space defined recursively as follows:
  - If $n = 0$, we set $D^m_0 (RR) = RR$ for all $m$, as usual;
  - If $m = 0$, we set $D^0_n (RR) = C_n (RR)$;
  - Let $m,n > 0$, and assume that both $D_(n-1)^m (RR)$ and $D_n^(m-1) (RR)$ are defined. Then we let $D^m_n (RR)$ be the set of all functions $f in CC(RR, D^m_(n-1)(RR))$ such that there is a function $f' in D^(m-1)_n (RR)$ which satisfies
    $
      (f(x + h) - f(x))/h st(h -> 0) f'(x) in H_(n-1) (RR)
    $
    for all $x in RR$, where *the convergence is taken in the space $H_(n-1) (RR)$*. Clearly, if $f, g in D^m_n (RR)$ and $alpha, beta in RR$, we have
    $
      (alpha f + beta g)' = alpha f' + beta g',
    $
    so in particular, $alpha f + beta g in D^m_n (RR)$.\
    We endow $D^m_n (RR)$ with the coarsest topology in which the maps
    $
      i : D^m_n (RR) &-> CC(RR, D^m_(n-1) (RR)), #h(3cm) d : D^m_n (RR) -> D^(m-1)_n (RR) #<maps>\
      f &|-> f #h(6.85cm) f |-> f'
    $
    are continuous. This topology will be called the _differential topology of order $m$._ We prove below that $D^m_n (RR)$ are Hausdorff topological vector spaces.
]

#lm[
  For all $m,n in NN_0$, we have $D_n^(m+1) (RR) subset D_n^m$, and the inclusion map
  $
    j : D^(m+1)_n (RR) -> D^m_n (RR)
  $
  is continuous, meaning that the topology on $D^(m+1)_n (RR)$ is finer than the topology induced from $D^m_n (RR)$.
]
#pf[
  We prove by induction over $n$. Consider the following cases:
  + $n = 0$. Then we have $D_0^(m+1) (RR) = D_0^n (RR) = RR$, and the statement holds;
  + $m = 0$. Then we have
    $
      D_n^1 (RR) subset CC(RR, D_(n-1)^0 (RR)) = CC(RR, C_(n-1) (RR)) = C_n (RR) = D_n^0 (RR),
    $
    and the inclusion is continuous by the definition of differential topology.
  + $n, m > 0$, with the statement proven for $(m, n-1)$ and $(m-1, n)$. Let $f in D_n^(m+1) (RR)$. Then we have
    $
      f in CC(RR, D_(n-1)^(m+1) (RR)) subset CC(RR, D_(n-1)^m (RR)).
    $
    Moreover, since $f' in D_n^m (RR) subset D_n^(m-1) (RR)$, we see that $f in D_n^m (RR)$ by definition, so we have the inclusion $D_n^(m+1) (RR) subset D_n^m (RR)$. It only remains to show that the inclusion map $j : D_n^(m+1) (RR) -> D_n^m (RR)$ is continuous. This is equivalent to showing that the maps $i circ j$ and $d circ j$ are continuous, which is evident from the following commutative diagrams:
    #centering(shallow: false)[
      #let s1 = 1
      #let s2 = 1
      #let ll = 10pt
      #let pd = 1em
      #let np = (40pt, 40pt)
      #show: columns.with(2)
      #commutative-diagram(
        padding: pd, node-padding: np,
        node((0,0), $D_n^(m+1)(RR)$, "00"),
        node((0,s1), $D_n^m (RR)$, "01"),
        node((s2,0), $CC(RR, D_(n-1)^(m+1)(RR))$, "10"),
        node((s2,s1), $CC(RR, D_(n-1)^m (RR))$, "11"),
        arr("00", "01", $j$, label-pos: ll, "inj"),
        arr("00", "10", $i$, label-pos: -ll, "inj"),
        arr("01", "11", $i$, label-pos: ll, "inj"),
        arr("10", "11", $j$, label-pos: -ll, "inj"),
      )
      #colbreak()
      #commutative-diagram(
        padding: pd, node-padding: np,
        node((0,0), $D_n^(m+1) (RR)$, "00"),
        node((0,s1), $D_n^m (RR)$, "01"),
        node((s2,0), $D_n^m (RR)$, "10"),
        node((s2,s1), $D_n^(m-1)(RR)$, "11"),
        arr("00", "01", $j$, label-pos: ll, "inj"),
        arr("00", "10", $d$, label-pos: -ll),
        arr("01", "11", $d$, label-pos: ll),
        arr("10", "11", $j$, label-pos: -ll, "inj"),
      )
    ]
]

#cor[
  We have a chain of subspaces with each topology finer than the previous one:
  $
    C_n (RR) = D_n^0 (RR) <--^j D_n^1 (RR) <--^j D_n^2 (RR) <--^j D_n^3 (RR) <--^j ...
  $
]

#lm[
  For all $n, m in NN_0$, the topological space $D_n^m (RR)$ is Hausdorff.
] <diffhaus>
#pf[
  Since $C_n (RR)$ is Hausdorff and $i : D_n^m (RR) -> C_n (RR)$ is continuous and injective, we see that $D_n (RR)$ is also Hausdorff.
]

#lm[
  For all $m,n in NN_0$, the pointwise linear structure is compatible with the topology on $D_n^m (RR)$, making $D_n^m (RR)$ a topological vector space.
] <difftvs>
#pf[
  We prove by induction over $n$ and $m$. If $n = 0$, we have $D_0 (RR) = RR$ with the usual topology and linear structure. If $m = 0$, we have $D_n^0 (RR) = C_n (RR)$, which is a TVS. Suppose now that $m, n > 0$. We need to establish the continuity of the following two maps:
  $
    + : D_n^m (RR) times D_n^m (RR) -> D_n^m (RR), #h(2cm) dot : RR times D_n^m (RR) -> D_n^m (RR).
  $
  In turn, by the definition of the differential topology, this task is equivalent to proving that the maps $i circ (+), d circ (+), i circ (dot), d circ (dot)$ are continuous, where the maps $i$ and $d$ are defined in (@maps).\
  To this end, note that we have commutative diagrams
  #centering(shallow: false)[
    #let s1 = 2
    #let s2 = 1
    #let ll = 10pt
    #let pd = 1em
    #let np = (40pt, 40pt)
    #commutative-diagram(
      padding: pd, node-padding: np,
      node((0,0), $D_n^m (RR) times D_n^m (RR)$, "00"),
      node((0,s1), $D_n^m (RR)$, "01"),
      node((s2,0), $CC(RR, D_(n-1)^m (RR)) times CC(RR, D_(n-1)^m (RR))$, "10"),
      node((s2,s1), $CC(RR, D_(n-1)^m (RR))$, "11"),
      arr("00", "01", $(+)$, label-pos: ll),
      arr("00", "10", $i times i$, label-pos: -1.6*ll, "inj"),
      arr("01", "11", $i$, label-pos: 0.8*ll, "inj"),
      arr("10", "11", $(+)$, label-pos: -ll),
    )
    #v(1em)
    #commutative-diagram(
      padding: pd, node-padding: np,
      node((0,0), $D_n^m (RR) times D_n^m (RR)$, "00"),
      node((0,s1), $D_n^m (RR)$, "01"),
      node((s2,0), $D_n^(m-1) (RR) times D_n^(m-1) (RR)$, "10"),
      node((s2,s1), $D_n^(m-1) (RR)$, "11"),
      arr("00", "01", $(+)$, label-pos: ll),
      arr("00", "10", $d times d$, label-pos: -1.8*ll),
      arr("01", "11", $d$, label-pos: 0.8*ll),
      arr("10", "11", $(+)$, label-pos: -ll),
    )
    #v(1em)
    #commutative-diagram(
      padding: pd, node-padding: np,
      node((0,0), $RR times D_n^m (RR)$, "00"),
      node((0,s1), $D_n^m (RR)$, "01"),
      node((s2,0), $RR times CC(RR, D_(n-1)^m (RR))$, "10"),
      node((s2,s1), $CC(RR, D_(n-1)^m (RR))$, "11"),
      arr("00", "01", $(dot)$, label-pos: ll),
      arr("00", "10", $"id" times i$, label-pos: -2*ll, "inj"),
      arr("01", "11", $i$, label-pos: 0.8*ll, "inj"),
      arr("10", "11", $(dot)$, label-pos: -ll),
    )
    #v(1em)
    #commutative-diagram(
      padding: pd, node-padding: np,
      node((0,0), $RR times D_n^m (RR)$, "00"),
      node((0,s1), $D_n^m (RR)$, "01"),
      node((s2,0), $RR times D_n^(m-1) (RR)$, "10"),
      node((s2,s1), $D_n^(m-1) (RR)$, "11"),
      arr("00", "01", $(dot)$, label-pos: ll),
      arr("00", "10", $"id" times d$, label-pos: -2*ll),
      arr("01", "11", $d$, label-pos: 0.8*ll),
      arr("10", "11", $(dot)$, label-pos: -ll),
    )
  ]
  Since the down-then-right path in each diagram is continuous, the right-then-down paths are continuous as well, and we are done.
]

#th[
  Let $m,n in NN$. A curried function $f in H_n (RR)$ lies in the class $D_n^m (RR)$ if and only if its counterpart $tilde(f) : RR^n -> RR$ has continuous partial derivatives on $RR^n$, of all orders up to $m$. Moreover, for each $1 <= i_1 <= i_2 <= ... <= i_m <= n$, we have
  $
    &(partial^m tilde(f))/(partial x_(i_1) partial x_(i_2) ... partial x_(i_m))(x_1, x_2, ..., x_n)\
    = &f(x_1)...(x_(i_1 - 1))'(x_i_1)...(x_(i_2 - 1))'(x_i_2)...(x_(i_m - 1))'(x_i_m)...(x_n). #<difftrans>
  $
] <diffgamma>
#pf[
  If $n = 0$ or $m = 0$, the statement is trivial. Now let $n,m > 0$ and assume the statement proven for $(m,n-1)$ and $(m-1,n)$.\

  First, let $f in D_n^m (RR)$. We immediately see that $f in D_n^(m-1) (RR)$, and so, by the induction hypothesis, partial derivatives or order up to $m-1$ exist and are continuous on $RR^n$. Now, consider some $1 <= i_1 <= i_2 <= ..., <= i_m <= n$. It is not hard to see by definition that (@difftrans) holds. To show that the partial derivative with respect to $x_i_1, ..., x_i_m$ is continuous, consider $(h_1, h_2, ..., h_n) -> 0 in RR^n$, and a point $(x_1, ..., x_n) in RR^n$. By the continuity of $f$ and the definition of the differential topology, we have
  $
    f(x_1 + h_1) &st(h_1 -> 0) f(x_1) in D_(n-1)^m (RR),\
    &dots.v\
    f(x_1 + h_1)...(x_(i_1 - 1) + h_(i_1-1))' &st(h_1\, ...\, h_(i_1 - 1) -> 0) f(x_1)...(x_(i_1 - 1))' in D_(n - i_1 + 1)^(m-1) (RR),\
    &dots.v\
    &f(x_1 + h_1)...(x_(i_1 - 1) + h_(i_1-1))'...(x_(i_m - 1) + h_(i_m - 1))...(x_n + h_n)\
    st(h_1\, h_2\, ...\, h_n -> 0) &f(x_1)...(x_(i_1 - 1))'...(x_(i_m-1))'...(x_n) in D_0^0 (RR) = RR,\
  $
  so the partial derivative
  $
    (partial^m tilde(f))/(partial x_i_1 partial x_i_2 ... partial x_i_m)
  $
  is continuous on $RR^n$.\

  Conversely, suppose $f in H_n (RR)$ is such that $tilde(f) : RR^n -> RR$ lies in the class $C^m (RR^n)$. To show that $f in D_n^m (RR)$, we follow three steps:
  + For all $x_1 in RR$, we have $f(x_1) in D_(n-1)^m (RR)$. This is provided by the induction hypothesis, since the restriction of a $C^m$ function on a hyperplane is also a $C^m$ function.
  // + The function $f : RR -> D_(n-1)^m (RR)$ is continuous. To show this, consider a sequence ${x_k^((1))}_(k in NN) subset RR$ converging to $x^((1)) in RR$. 
  + The function $f : RR -> D_(n-1)^m (RR)$ is continuous. To show this, consider a sequence ${x_k^((1))}_(k in NN) subset RR$ converging to $x_0^((1)) in RR$. We aim to prove that $f(x_k^((1))) -> f(x_0^((1)))$ in $D_(n-1)^m (RR)$. This is equivalent to showing that
    $
      f(x_k^((1))) -> f(x_k^((1))) in CC(RR, D_(n-2)^m (RR)) #h(10pt) "and" #h(10pt) f(x_k^((1)))' -> f(x_0^((1)))' in D_(n-1)^(m-1) (RR).
    $ <twocond>
    The latter of these conditions holds by the induction hypothesis, since
    $
      (partial tilde(f))/(partial x_2)(x_1, ..., x_n) = (partial tilde(f(x_1)))/(partial x_2)(x_2, ..., x_n) =_(#hs #[by (@difftrans)] #hs) f(x_1)'(x_2)...(x_n),
    $ <par2>
    and $partial tilde(f)\/partial x_2$ is continuous, which means that the map $x |-> f(x)'$ is continuous. To prove the former condition in (@twocond), we again consider a sequence $x_k^((2)) -> x_0^((2)) in RR$ and aim to prove
    $
      f(x_k^((1)))(x_k^((2))) -> f(x_0^((1)))(x_0^((2))) in D_(n-2)(RR),
    $
    which (unless $n = 2$) is again equivalent to
    $
      f(x_k^((1)))(x_k^((2))) -> f(x_k^((1)))(x_k^((2))) #h(10pt) "and" #h(10pt) f(x_k^((1)))(x_k^((2)))' -> f(x_0^((1)))(x_0^((2)))'.
    $
    The latter follows from the induction hypothesis and the continuity of $partial tilde(f)\/partial x_3$, similarly to (@par2), and the former can again be expanded further. This chain leads us finally to the convergence
    $
      f(x_k^((1)))(x_k^((2)))...(x_k^((n))) -> f(x_0^((1)))(x_0^((2)))...(x_0^((n))) in RR,
    $
    which is evident since $f in C_n (RR)$ by @cogamma. Hence we see that $f$ lies in $CC(RR, D_(n-1)(RR))$. We have also established (@difftrans) for $f$ and $i >= 2$, via (@par2).
  + Finally, we need to find $f' in D_n^(m-1) (RR)$ such that
    $
      (f(x + h) - f(x))/h st(h -> 0) f'(x) in H_(n-1)(RR)
    $ <conv>
    for all $x in RR$. Indeed, following (@difftrans), let us define $f' := gamma(partial tilde(f)\/partial x_1)$. We immediately see by the induction hypothesis that $f'$ so defined lies in $D_n^(m-1) (RR)$. To see that (@conv) holds, consider $x_1, ..., x_n in RR$ and write
    $
      f'(x_1)(x_2)...(x_n) &= (partial tilde(f))/(partial x_1)(x_1, ..., x_n)\
      &= lim_(h -> 0) (tilde(f)(x_1 + h, x_2, ..., x_n) - tilde(f)(x_1, ..., x_n))/h\
      &= (lim_(h -> 0) (f(x_1 + h) - f(x_1))/h)(x_2)...(x_n),
    $
    and we are done.
]

#bibliography("bibliography.yml")

= Appendix <app>

== The language of filters <filapp>

#def[
  Let $X$ be a set. A _filter_ on $X$ is a non-empty set $F subset 2^X$ which is closed under supersets and finite intersections, and does not contain the empty set. The set of all filters on $X$ will be denoted by $FF(X)$.
]

#def[
  Let $X$ be a set. A family $cal(B) subset 2^X$ is called a _filter base_ if it does not contain the empty set and is closed under finite intersection. The filter $[cal(B)]$ _generated_ by $cal(B)$ is defined as the collection of all supersets of sets from $cal(B)$.\
  If $cal(B) = {{x}}$ where $x in X$, the filter $[x] = [{{x}}]$ is called the _universal filter_ of $x$.\
  If $f : X -> Y$ is a map and $F in FF(X)$ is a filter on $X$, then ${f(A) mid(|) A in F}$ is a filter base that generates the _image filter_ denoted $f(F)$.
]

#def[
  Let $X$ be a topological space. Then we say that a filter $F$ on $X$ _converges_ to a point $x in X$, and write $F -> x$, if it contains all open neighborhoods of $x$.
]

#rem[
  The language of filters is expressive enough to encode all topological properties. For example @bou1:
  - A sequence ${x_n}_(n = 1)^oo$ converges to a point $x in X$ iff the filter
    $
      F = {A subset X mid(|) x_n in A "for all but finitely many" n}
    $
    converges to $x$. This filter $F$ is called the _derived filter_ of ${x_n}_(n = 1)^oo$.
  - A subset $E subset X$ is closed if for every point $x in E$ there is a filter $F in FF(X)$ converging to $x$ such that $A inter E != diameter$ for all $A in F$.
  - A topological space $X$ is compact iff every filter $F$ on $X$ is contained in a convergent filter on $X$.
  - A function $f : X -> Y$ between topological spaces is continuous iff it preserves convergent filters, i.e. $F -> x in X$ implies $f(F) -> f(x) in Y$.
]

#lm([see @bou1, page 74])[
  Let $X$ be a set and $f_i : X -> Y_i$ be a family of maps, where $Y_i$ are topological spaces. Let $X$ be endowed with the coarsest topology such that $f_i$ is continuous for each $i$. Then a filter $F in FF(X)$ converges to $x in X$ if and only if $f_i (F)$ converges to $f_i (x)$ for all $i$.
]

== Topological vector spaces <tvsapp>

We assume that the reader is familiar with the definition and basic properties of topological vector spaces. Here we list some results that will be 

== The topology of pointwise convergence <pcapp>

#def([pointwise convergence topology, see @bou2])[
  Let $X$ be a set, $Y$ a topological space, and denote by $SS(X,Y)$ the set of functions from $X$ to $Y$. For each $x in X$ and each open set $U subset Y$, let $V(x, U)$ be the set of all functions $f in SS(X,Y)$ such that $f(x) in U$. The collection
  $
    {V(x,U) mid(|) x in X, U subset Y}
  $
  forms a subbase of a topology on $SS(X,Y)$, called the _topology of pointwise convergence._
]

#rem[
  Let $X$ be a set and $Y$ a topological space. It is not hard to see that a filter $F in FF(SS(X,Y))$ converges to a function $f in SS(X,Y)$ if and only if, for any $x in X$, the filter $F(x) = [{A(x) mid(|) A in F}]$ converges to $f(x) in Y$.
]

#lm[
  Let $X$ be a set and $Y$ a Hausdorff topological space. Then $SS(X,Y)$ is also Hausdorff.
] <pwhaus>
#pf[
  Consider two functions $f, g in SS(X,Y)$ such that $f != g$. This implies that there is $x_0 in X$ such that $f(x_0) != g(x_0)$. Since $Y$ is Hausdorff, there are neighborhoods $U_f in.rev f(x_0)$ and $U_g in.rev g(x_0)$ such that $U_f inter U_g = diameter$. It then follows that $f in V(x_0, U_f)$, $g in V(x_0, U_g)$, and $V(x_0, U_f) inter V(x_0, U_g) = diameter$.
]

#lm[
  Let $X$ be a set and let $Y$ be a real topological vector space. Then $SS(X,Y)$ is also a real topological vector space with respect to the topology of pointwise convergence and the pointwise linear structure.
] <pwtvs>
#pf[
  We need to show that the maps $+ : SS(X,Y) times SS(X,Y) -> SS(X,Y)$ and $dot : RR times SS(X,Y) -> SS(X,Y)$ are continuous.\
  To begin, consider two filters $F_1, F_2 in FF(SS(X,Y))$, converging to $f_1$ and $f_2$ respectively. To show that $F_1 + F_2$ converges to $f_1 + f_2$, consider $x in X$. We have
  $
    (F_1 + F_2)(x) &= [{(A + B)(x) mid(|) A in F_1, B in F_2}]\
    &= [{A(x) + B(x) mid(|) A in F_1, B in F_2}]\ 
    &= F_1 (x) + F_2 (x) -> f_1 (x) + f_2 (x) = (f_1 + f_2)(x).
  $
  This shows that the addition operation is continuous. Scalar multiplication is continuous by a similar argument.
]

== The compact-open topology <coapp>

#def([compact-open topology, see @bou2])[
  Let $X$ and $Y$ be two topological spaces, and by $CC(X,Y)$ denote the set of all continuous functions from $X$ to $Y$. For each compact set $K subset X$ and each open set $U subset Y$, let $V(K,U)$ be the set of all functions $f in CC(X,Y)$ such that $f(K) subset U$. The collection
  $
  {V(K,U) mid(|) K subset X, U subset Y}
  $
  forms a subbase of a topology on $CC(X,Y)$, called the _compact-open_ topology.
]

#rem[
  Clearly, the topology of pointwise convergence on $CC(X,Y)$ is coarser than the compact-open topology.
]

#prop([see @bb])[
  Let $X$ and $Y$ be topological spaces such that $X$ is locally compact and $Y$ is regular. Then a filter $F in FF(CC(X,Y))$ converges to a function $f in CC(X,Y)$ if and only if, for any filter $P in FF(X)$ converging to $p in X$, we have $F(P) -> f(p)$ in $Y$, where the filter $F(P)$ is based on
  $
    {A(B) mid(|) A in F, B in P} = {{a(b) mid(|) a in A, b in B} mid(|) A in F, B in P}.
  $
] <cofilter>

#prop([see @bou2, page 302])[
  Let $X, Y, Z$ be topological spaces such that $X$ is Hausdorff and $Y$ is locally compact. Then the map
  $
    gamma : CC(X times Y, Z) -> CC(X, CC(Y, Z))
  $
  defined as $gamma(f)(x)(y) = f(x,y)$, is well-defined and is a homeomorphism.
] <curry>

#lm[
  Let $X, Y$ be topological spaces such that $Y$ is Hausdorff. Then the space $CC(X,Y)$ is also Hausdorff.
] <cohaus>
#pf[
  The compact-open topology on $CC(X,Y)$ is finer than the topology of pointwise convergence, and the latter is Hausdorff, which implies that the former is Hausdorff.
]

#lm[
  Let $X$ be a topological space and $Y$ a real topological vector space. Then $CC(X,Y)$ is also a real topological vector space with respect to the pointwise linear structure and the compact-open topology.
] <cotvs>
#pf[
  We will show that the map $+ : CC(X,Y) times CC(X,Y) -> CC(X,Y)$ is continuous. Let $F_1, F_2 in FF(CC(X,Y))$ converge to $f_1 in CC(X,Y)$ and $f_2 in CC(X,Y)$ respectively. For any filter $P in FF(X)$ converging to $p in X$, we have
  $
    (F_1 + F_2)(P) &= [{(A_1 + A_2)(B) mid(|) A_i in F_i, B in P}]\
    &supset [{A_1 (B_1) + A_2 (B_2) mid(|) A_i in F_i, B_i in P}]\
    &= F_1 (P) + F_2 (P) -> f_1 (p) + f_2 (p) = (f_1 + f_2)(p).
  $
  The continuity of scalar multiplication is proven similarly.
]


  // We employ induction over $n$. If $n = 1$, the statement clearly holds. Now, consider $n >= 2$ and assume that the statement holds for $n-1$.\
  // First, let $f in D_n (RR)$ and $(x_1, x_2, ..., x_n) in RR^n$. For $i >= 2$, we have
  // $
  //   (partial tilde(f))/(partial x_i)(x_1, ..., x_n) &= lim_(h -> 0) (tilde(f)(x_1, ..., x_i + h, ..., x_n) - tilde(f)(x_1, ..., x_n))/h\
  //   &= lim_(h -> 0) (tilde(f(x_1))(x_2, ..., x_i + h, ..., x_n) - tilde(f(x_1))(x_2, ..., x_n))/h\
  //   &= (partial tilde(f(x_1)))/(partial x_i)(x_2, ..., x_n) = f(x_1)...(x_(i-1))'(x_i)...(x_n)
  // $
  // by the induction hypothesis, since $f(x_1) in D_(n-1)(RR)$. For the derivative with respect to $x_1$, we have
  // $
  //   f'(x_1)(x_2)...(x_n) &= (lim_(h -> 0) (f(x_1 + h) - f(x_1))/h)(x_2)...(x_n)\
  //   &= lim_(h -> 0) (f(x_1+h)(x_2)...(x_n) - f(x_1)...(x_n))/h\
  //   &= lim_(h -> 0) (tilde(f)(x_1 + h, x_2, ..., x_n) - tilde(f)(x_1, ..., x_n))/h = (partial tilde(f))/(partial x_1)(x_1, ..., x_n),
  // $
  // so $partial tilde(f)\/partial x_1 = f'$, and we see that (@difftrans) holds. We also immediately observe that $partial tilde(f)\/partial x_1$ is continuous by @cogamma, since $f' in C_n (RR)$. It remains to show that the derivatives with respect to $x_2, ..., x_n$ are continuous. To this end, let $(h_1, ..., h_n) -> 0 in RR^n$. Since $D_n (RR) subset CC(RR, D_(n-1)(RR))$, the function $f : RR -> D_(n-1)(RR)$ is continuous, and so we have the convergence
  // $
  //   f(x_1 + h_1) st(h_1 -> 0) f(x_1) in D_(n-1)(RR).
  // $
  // Now, since the map $d : D_(n-1)(RR) -> C_(n-1)(RR)$ is continuous, the above implies
  // $
  //   f(x_1 + h_1)' st(h_1 -> 0) f(x_1)' in C_(n-1)(RR).
  // $
  // From here, by @simul, we have
  // $
  //   &(partial tilde(f))/(partial x_2)(x_1 + h_1, ..., x_n + h_n)\
  //   = &f(x_1 + h_1)'(x_2 + h_2)...(x_n + h_n) st(#h(5pt) h_1\, h_2\, ... h_n -> 0 #h(5pt)) f(x_1)'(x_2)...(x_n) = (partial tilde(f))/(partial x_2)(x_1, ..., x_n).
  // $
  // A similar argument shows that the partial derivatives with respect to $x_3, ..., x_n$ are continuous as well.
  //
  // Now, we prove the other direction. Consider $f in H_n (RR)$ such that $tilde(f) : RR^n -> RR$ has continuous partial derivatives. To show that $f in D_n (RR)$, we follow three steps:
  // + For all $x_1 in RR$, we have $f(x_1) in D_(n-1)(RR)$. This holds by the induction hypothesis, since $tilde(f(x_1)) : RR^(n-1) -> RR$ clearly has continuous partial derivatives, being a restriction of $tilde(f)$.

// #prop([see @bb, page 28])[
//   Let $X$ be a convergence space and let $Y$ be a Hausdorff convergence space (i.e. every filter in $Y$ converges to at most one point). Then $CC(X,Y)$ is also a Hausdorff convergence space.
// ] <haus>

// #prop([see @bb, page 29])[
//   Let $X$ be a convergence space and $Y$ be a convergence vector space, i.e. a set endowed with both structures such that the operations $+ : Y times Y -> Y$ and $dot : RR times Y -> Y$ are continuous. Then $CC(X,Y)$ is also a convergence vector space.
// ] <tvs>
